### ISSUE TITLE
Make login feature

### ISSUE THREAD

**Issue by SeulGeek** [SeulGeek/FavRev#5]
**Steps**
- [x] Make UI
- [x] Connect firebase
   - Ref) 
     [Android Studio Firebase 연동 (1)](https://lakue.tistory.com/37)
     [Android Studio Firebase 연동 (2)](https://lakue.tistory.com/38?category=853542)

     [Firebase Guide](https://firebase.google.com/docs/guides?authuser=0)
     [Firebase Sample](https://firebase.google.com/docs/samples?authuser=0)

-  [ ] Implement sign up feature at first
-  [ ] Make login feature whether it is working well on firebase
-  [ ] Check validation

**Comment by SeulGeek** [comment]
it's successful to connect with firebase. let me make signup feature first (#7)
![image](https://user-images.githubusercontent.com/64777031/109507572-3a0c1500-7ae2-11eb-9497-3b34f8c1a905.png)

**Comment by SeulGeek** [comment]
**TODO (After implementation for sing up feature) :** 

- [ ] Check validation when user put email
 > com.google.firebase.database.DatabaseException: Invalid Firebase Database path: seulgeek@gmail.com. Firebase Database paths must not contain '.', '#', '$', '[', or  #']'

![image](https://user-images.githubusercontent.com/64777031/109507668-4f813f00-7ae2-11eb-9225-db50c93eb90c.png)

- [ ] Hide password when user put it (like ******)
![image](https://user-images.githubusercontent.com/64777031/109507966-a71faa80-7ae2-11eb-8db5-dd5ff6c498bc.png)
